### ISSUE TITLE
2017 斯坦福李飞飞视觉识别课程 链接已经失效

### ISSUE THREAD

**Issue by bcho** [caicloud/mlsys-ladder#9]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

这个[链接](https://study.163.com/course/introduction.htm?courseId=1004697005&_trace_c_p_k2_=186f7182b63648daa0d42d0058413cc0)点击过去会显示已经过期。或者可以考虑换成 bilibili 上面的：

https://www.bilibili.com/video/av13260183/

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
不能保证 Bilibili 上的视频是否是有版权的，比较难办

**Comment by bcho** [comment]
How about https://www.youtube.com/watch?v=vT1JzLTH4G4 ? But yes, this requires extra effort to access 😅

**Comment by gaocegege** [comment]
YouTube 上的一定是可以的，但是我们之前用了网易的是因为网易课程上有中文翻译。现在如果没有了就很尴尬，这段时间我去看看网易上究竟是 URL 变动了还是真的没有了

**Comment by gaocegege** [comment]
/assign @gaocegege 

调研国内有版权的中文翻译课程

**Comment by gaocegege** [comment]
@bcho Thanks for the issue. 如果有任何进展请继续回复

**Comment by bcho** [comment]
👍

**Comment by kz33** [comment]
@gaocegege https://cloud.tencent.com/edu/learning/course-1039 这里有中文版的。可以代替之前网易云课堂的。

**Comment by gaocegege** [comment]
好的，晚上回去替换一下
